### ISSUE TITLE
Character encoding differences

### ISSUE THREAD

**Issue by Solinx** [netlify/netlify-lambda#115]
Netlify Lambda has been really helpful to us, so many thanks for making this available! Unfortunately we did encounter one potential issue.

While developing locally we encountered character encoding issues. Like `Ö` would turn into `Ã–` when outputted to the browser. We were still looking at encoding solutions when someone found out that these encoding issues disappear when we deploy our function to Netlify and have it run in a live environment.

To be honest I don't know whether it's `netlify-lambda` or something else in our local setup. We've got too much on our plate to look into this and it's not our field of expertise anyhow. I hope it helps you to improve this package!

**Comment by sw-yx** [comment]
oh wow, thanks for the kind words. @futuregerald - any experience with this? what can we do to fix?

**Comment by futuregerald** [comment]
Thanks for the report. Which OS are you building on? Do you have any examples that we can use to reproduce this issue?

**Comment by sw-yx** [comment]
@Solinx - closing this for now but thanks for the report. we are releasing a new way to deploy functions this week - curious to see if that helps you. please check it out when its launched!

**Comment by woodscreative** [comment]
Here in 2024 just ran into this very problem. Had to set headers in the response for the fix locally:
```
headers: {
    "Content-Type" : "application/json; charset=utf-8"
}
```

**Comment by nolessafool** [comment]
@woodscreative - While I no longer work for Netlify, I think that if you're still using netlify-lambda, it's past time to migrate as this tool has been deprecated (see the README on this repo for details).  

Can you explain the workflow that has you still needing to use this tool, or if not, explain what tools you are using, so the team who works on functions can make sure the bug gets surfaced on some software that is still actively maintained and intended for use?  cc @minivan for visibility since I probably won't notice a followup.
