### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number

### ISSUE THREAD

**Issue by harvey56** [netlify/netlify-lambda#183]
Hello,

I'm trying to make requests to my firestore database in my lambda function. 

I can declare a document reference as follows : 
`let userRef = db.collection('users').doc('hgyrirkignmght');`
`console.log("userRef: ", userRef); // this works`

However, I cannot make a `get()` request : 
```
userRef.get()
    .then(function(doc) {
      if (doc.exists) {
          console.log("Document data:", doc.data());
      } else {
          // doc.data() will be undefined in this case
          console.log("No such document!");
      }
    })
    .catch(function(error) {
        console.log("Error getting document:", error);
    });
```
This returns the error message as stated in the title : 
```
Error getting document: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
```
I can't tell if the error is netlify related or firebase related.

I understand from this thread (https://github.com/netlify/netlify-lambda/issues/112) that there may be issues when making firebase requests using netlify-lambda. So, I tried netlify-dev as documented. I set it up (I have a .netlify folder in my server folder). I set the proxy target as `http://localhost:34567`. Now, if I go to http://localhost:34567/myfunction, I still have the same error message as with netlify-lambda.

Can we know for sure if the issue comes from netlify or firebase ? Any suggestion what can be done ?

I'm aware of an alternative way of using firebase (as documented here https://firebase.google.com/docs/projects/api/workflow_set-up-and-manage-project#before-you-begin). However, it's in beta and it doesn't work either. `const resp = await rp(options);` would return an empty object, although I do have projects (i.e. `projects.length !== 0`). But here again, the issue may be firebase related, I'm not sure.

Thanks for your kind help

**Comment by sw-yx** [comment]
first of all, can we make sure that you're hitting  the right url. the function should be at `http://localhost:34567/.netlify/functions/myfunction`

**Comment by JeffML** [comment]
The solution here worked for me, though I am still trying to figure out what my GOOGLE_APPLICATION_CREDENTIALS path variable should be: is it root? lambda folder?  ./<path>, /<path>, or just <path>? Or do I set it in netlify.toml? or in my start command in package.json?

**Comment by sw-yx** [comment]
no idea. refer to their docs i guess. good luck

**Comment by frankcalise** [comment]
Hey I can maybe help here. I just battled a bunch of firebase admin sdk + netlify function errors along the way, primarily because I wasn't too familiar with cloud functions.

For that error you're seeing about the first argument, may I ask what you're returning as the body to the response? It should be a string or if you want a JSON object, JSON.stringy it (or a buffer is allowed also).

Also the firebase app only wants to be initialized one time, so you can do something like this:
`const admin = require("firebase-admin");
const serviceAccount = require("./firebase-dev.json");
console.log(admin.apps.length)
const app = !admin.apps.length
? admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  })
: admin.app();


export default app`

and then use it in your function js
`import firebase from './utils/firebase'

exports.handler = async function(event) {
//...
  const querySnapshot = await firebase
    .firestore()
    .collection(`users`)
    .where("subscription_status", "==", "trialing")
    .get();
//return etc
}

**Comment by antoinerousseau** [comment]
Fyi I had the exact same error because I didn't have a `functions` key in my `netlify.toml`. In case it helps anyone.

**Comment by YashTitanium7** [comment]
> Fyi I had the exact same error because I didn't have a `functions` key in my `netlify.toml`.
> In case it helps anyone.
> Netlify could throw a better error though.

Thank you so much buddy
