### ISSUE TITLE
netlify serve doesn't work with apollo v3

### ISSUE THREAD

**Issue by PinkaminaDianePie** [netlify/netlify-lambda#484]
Apollo v3 depends on `serverless-express` package, which requires `requestContext` field to be present on `event` param of AWS handler. Netlify doesn't provide such a field: https://github.com/vendia/serverless-express/issues/427

That make impossible to upgrade to Apollo v3

**Comment by erezrokah** [comment]
Hi @PinkaminaDianePie, the `serve` command is deprecated, see https://github.com/netlify/netlify-lambda#netlify-lambda-serve-legacy-command

I recommend switching to `netlify dev`. See [here](https://cli.netlify.com/netlify-dev/) for more details.
If that doesn't satisfy your use case, you can open a new issue [here](https://github.com/netlify/cli/issues/new/choose).

**Comment by PinkaminaDianePie** [comment]
@erezrokah please don't advise to use broken solutions. `netlify dev` doesn't support webpack so it's not suitable for real-world cases. I used netlify for 3 different projects and `netlify dev` failed to handle any of them, while `netlify-lambda serve` worked really well for all of them. A fancy solution that doesn't work is worse than not that fancy solution that works fine. Please don't advise people to use something that doesn't work, you will just waste their time.

**Comment by erezrokah** [comment]
Hi @PinkaminaDianePie, can you open an issue on the CLI repo with your use cases so we can have a look?

You should be able to work with `netlify dev` **_and_** `netlify-lambda` (and keep your Webpack configuration), see https://github.com/netlify/netlify-lambda#when-to-use-netlify-dev-or-netlify-lambda-or-both

To clarify - the suggestion is not to stop using `netlify-lambda`. It's to use `netlify dev` for development as it supports invoking `netlify-lambda` to generate functions.

Also `netlify dev` has built-in support for `esbuild` (see [here](https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/)), so that might be suitable for your use case too.

**Comment by PinkaminaDianePie** [comment]
@erezrokah last time when i tried it (about half a year ago) I wasn't able to mix `netlify dev` and `netlify-lambda` - `netlify dev` just killed my PC by an infinite spawn of `node` processes, required a hard reset. But I will try it out again for 4th time, may be now it will work at least with `netlify-lambda`. BTW `esbuild` is not an option because it's not configurable. Webpack allows to add a lot of different stuff, like different file extensions, monorepo setup with common directories (importing outside of lambdas directory) and much more. `esbuild` could work for "hello world" projects, but would be probably never suitable for real-world apps.

**Comment by erezrokah** [comment]
Thanks @PinkaminaDianePie, I think you might have experienced https://github.com/netlify/cli/issues/904 which had since been resolved.

As for `esbuild` you can track progress in https://github.com/netlify/zip-it-and-ship-it, and you might also be interested in the discussion [here](https://github.com/netlify/zip-it-and-ship-it/pull/553).

I can confirm we have customers using `esbuild` successfully for real world apps (enjoying the much faster build times), but we're constantly evaluating our approach and I appreciate the feedback.

**Comment by PinkaminaDianePie** [comment]
@erezrokah working `esbuild` is just a survivorship bias. There is a lot of people for who it won't work. You even attached an issue as proof of that - normal graphql workflow doesn't work with `esbuild`, and graphql is a huge part of the serverless ecosystem. What about other file extensions? What about different repo setups? You will require everyone to change their workflow to be compatible with `esbuild`? That's counterproductive - zero config setup should making the work simpler, not to drain dev times to find a workarounds how to make their repo compatible with esbuild. I don't need a tool which has a fast build time, but doesn't work. I'd prefer a tool which might be slower, but would work for my current case, and will give me a confidence that it would work for other use cases which I might have in the future. `netlify-lambda` was such kind of a tool, but was deprecated in a favour of another tool, which can't give me such a confidence. It might be faster, fancier, have a single command to run everything, but it fails on a very basic thing - it doesn't work with my current work flow, and there is no guarantees that it will support different use cases I might have in the future. So even if this time `netlify dev` would work for me, it would be really sad to switch to it, `netlify-lambda` is just better. DX is not only having a magical command what will run everything for you without a config. DX is also an ability to support different workflows and project structures. And `netlify dev` is much worse at it than `netlify-lambda`

**Comment by erezrokah** [comment]
Hi @PinkaminaDianePie, thank you for your feedback, but I think this issue is getting off topic.

If you have a specific use case that doesn't work with `netlify dev` or `esbuild` I recommend opening an issue either in the CLI repo or in https://github.com/netlify/zip-it-and-ship-it, so we can have a productive discussion about possible solutions.

**Comment by PinkaminaDianePie** [comment]
@erezrokah fyi: i've tried `netlify dev` for the 4th time and it doesn't work again. There is a way to build functions using `netlify-lambda`, but there is no way to watch and rebuild on changes. Instead of using webpack native `watch` mechanism, based on dependencies, `netlify dev` just runs it's own mechanism based on directories, so if lambda using any code outside of it, like common code between servers in monorepo it fails to detect the change. So the only way is to re-run `netlify dev` manually after every single change. Please, don't advise people to use it again. `netlify-lambdas` works, `netlify dev` fails every single time due to different reasons. If you are not willing to support `netlify-lambdas` by yourself - just ask people to submit PRs by themselves or if you don't even wanna mess up with PRs - you can just tell people to fork it and maintain it by themselves. But don't tell them to use `netlify dev` instead - that's just a crap, I have no other words. I tried it so many times for multiple projects for about a year, but it fails every single time. And even to debug it I have to go through the code, there is no way to understand if it works or not without it. I don't really like to be rude, but asking people to waste their time by switching from a working tool to a broken one is not nice as well.

**Comment by ehmicky** [comment]
@PinkaminaDianePie I have edited your comment to adhere to our [Code of conduct](https://github.com/netlify/netlify-lambda/blob/main/CODE_OF_CONDUCT.md). We understand your frustration, but please keep the language courteous and the discussion productive.
