### ISSUE TITLE
Running tests/CI suite

### ISSUE THREAD

**Issue by Tyler-Churchill** [netlify/netlify-lambda#49]
I may be missing an obvious configuration option.

For running this server for testing, how would one ensure that the webpack watch stops executing so everything can exit correctly?

I can add a pull request that adds another cli command, something like start:ci or something like that.

**Comment by iiroj** [comment]
If you absolutely need this, I recently created my own alternative, [lambda-dev](https://www.npmjs.com/package/lambda-dev). It's main difference is that it's not Netlify-specific and doesn't read the `netlify.toml` file, but otherwise it similarly supports serving (with configurable prefix) and building through webpack/babel.

Since adding tests, I had to add support for controlling webpack's watch mode. I just released `v1.4.0` and added a `--watch false` flag to disable watching.

**Comment by 8eecf0d2** [comment]
like @iiroj I've also created my own alternative [8eecf0d2/netlify-local](https://github.com/8eecf0d2/netlify-local) which _does_ read `netlify.toml` and now has an API for test runners which you can use to start / stop the Server and manage the Webpack build process.

See 8eecf0d2/netlify-local#6 for more about the API.

**Comment by sw-yx** [comment]
hi @Tyler-Churchill, sorry for the super delayed repsonse. i'm just picking up on all the issues now. will link to you from the readme but i have no official testing solution in the repo right now.
