### ISSUE TITLE
Usage in monorepo

### ISSUE THREAD

**Issue by Levino** [netlify/netlify-lambda#55]
I have a `lerna` monorepo.

My functions package is in `packages/functions`. My functions source is in `packages/functions/src`. I build the functions with `netlify-lambda` via a script in the file `packages/functions/package.json`. I want the functions to be build to `packages/functions/build` so I add a `netlify.toml` with this content:
```toml
[build]
  functions = "build"
```
When I run `netlify-lambda serve ./src` from `packages/functions` all is fine. I also add a `postinstall` script to run `netlify-lambda build ./src` which creates the correct files in `packages/functions/build` when `yarn` is run.

But when I try to deploy to netlify, netlify takes the `netlify.toml` from the folder `packages/functions` and tries to find the functions in `build` (at the project root) and finds no functions.

If I do not commit the `netlify.toml` (to just use it locally), the `postinstall` script does not work any more, because it requires a `netlify.toml` (in `package/functions`).

So baseline is: One cannot use this tool with a monorepo.

I suggest to stop (**ab**)using the `netlify.toml` for a build configuration and make the cli tool take two parameters:

```bash
netlify-lambda build src target
```

**Comment by Levino** [comment]
And I found a hack to fix it too:
Just add a second `netlify.toml` with the following content to the root:
```toml
[build]
  functions = "packages/functions/build"
```
This will overwrite the local `netlify.toml`.

**Comment by sw-yx** [comment]
glad you found a fix!

`netlify.toml` is very central to how netlify works though, so unlikely to incorporate your suggestion anytime soon. will keep it in mind though.

**Comment by Levino** [comment]
I am just saying that the build command should not read the output path from the netlify.toml. At least it should be able to override the output path as I suggested. The netlify.toml should define where netlify can find the functions, nothing more. I do not see any potential issue in changing the behavior in the way that I suggested. Your point that the netlify.toml is essential to how netlify works is correct, but has nothing to do with what I suggested.

**Comment by 8eecf0d2** [comment]
@Levino If your `packages/functions/netlify.toml` contained the following:
```toml
[build]
  functions = "packages/functions/build"
```

Would this work in production? or if not, what does work for you in production? I think we should start from there and then attempt to replicate the experience in **netlify-lambda**. _Imo, parsing the toml file is acceptable for this package so long as it's parsed the same way as production._

**Comment by Levino** [comment]
[Here it is](https://github.com/Levino/netlify-functions-multirepo-example). Please open a PR if you can make your solution work @8eecf0d2

**Comment by Levino** [comment]
> @Levino If your `packages/functions/netlify.toml` contained the following:
> 
> ```toml
> [build]
>   functions = "packages/functions/build"
> ```
> 
> Would this work in production?

Then in production netlify would look for the functions in `packages/functions/build` but the functions would be in `packages/functions/packages/functions/build` and all goes south.

**Comment by sw-yx** [comment]
keeping this open :)

**Comment by 8eecf0d2** [comment]
Thanks for the example!

I've tested it out at [clever-brown-0c43f1.netlify.com](https://clever-brown-0c43f1.netlify.com) and it's all making sense now - _I'll try and explain what I understand for others who read this._

- [Publish](https://clever-brown-0c43f1.netlify.com) returns **200**
- [getData Function](https://clever-brown-0c43f1.netlify.com/.netlify/functions/getData) returns **200**

Locally **netlify-lambda** works from the _repo root_
```bash
netlify-lambda serve packages/functions/src
```
And also from the _functions package root_
```
cd packages/functions
netlify-lambda serve src
```

This boils down to wanting to remove the `packages/functions/netlify.toml` file because it is **only** being used by **netlify-lambda** and typically the processing directory during development with a monorepo is the `package/<name>` which means the `packages/functions/netlify.toml` must exist for **netlify-lambda** to work correctly.

Based on what I know now and about the use case I'd be in favour of allowing a `-b --build` / `-o --out` style command (which _should_ solve every use case), but additionally a `-r --root` style command.

- `-b --build`, `-o --out`
```bash
cd packages/functions
netlify-lambda serve src -o build
```
_could also just be a second argument `netlify-lambda serve src build`_

- `-r --root`
```bash
cd packages/functions
netlify-lambda serve src -r ../../
```

I'll wait to hear thoughts from @sw-yx or other Netlify people before writing a PR but this sounds reasonable to me.

**Comment by sw-yx** [comment]
i gotta say i have no strong opinion about this, i just dont have this usecase nor do i expect it to be common. pinging @DavidWells and @biilmann on whether this is something we'd wanna do
